[package]
name = "peg_solitaire"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.35", features=["persistence"] }
#egui = { version = "0.35" }
#egui_extras = { version = "0.35", features=["all_loaders"] }
kudchuet = { path = "../../kudchuet" }
bitboard = {path="../../bitboards/bitboard"}
bitboard_proc_macro = {path="../../bitboards/bitboard_proc_macro"}
#bitboard = {git = "https://github.com/ultrasuperpingu/bitboards.git"}
#bitboard_proc_macro = {git = "https://github.com/ultrasuperpingu/bitboards.git"}
fastrand = "2.4"
egui_field_editor = {git = "https://github.com/ultrasuperpingu/egui_field_editor.git", features=["filepicker"] }
#egui_field_editor = {path="../../egui_inspect/egui_field_editor", features=["filepicker"] }
#egui_field_editor = "0.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Document", "HtmlCanvasElement"] }

[lints]
workspace = true

[lib]
name = "peg_solitaire"

[[bin]]
name = "peg_solitaire"
path = "src/main.rs"