[package]
name = "taquin"
version = "0.1.0"
edition = "2024"

[dependencies]
kudchuet = { path = "../../kudchuet" }
fastrand = "2.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Document", "HtmlCanvasElement"] }

[lints]
workspace = true

[lib]
name = "taquin"

[[bin]]
name = "taquin"
path = "src/main.rs"