[env]
RUST_MIN_STACK = "16777216"

#[build]
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]

[target.wasm32-unknown-unknown]
rustflags = [] 
# rustflags = ["-C", "target-feature=+simd128"]
# rustflags = ["-C", "target-feature=+simd128,+bulk-memory,+mutable-globals"]