[package]
name = "hex_game"
version = "0.1.0"
edition = "2021"

[dependencies]
kudchuet = { path = "../../kudchuet" }
bitboard = {path="../../bitboards/bitboard"}
bitboard_proc_macro = {path="../../bitboards/bitboard_proc_macro"}
#bitboard = {git = "https://github.com/ultrasuperpingu/bitboards.git"}
#bitboard_proc_macro = {git = "https://github.com/ultrasuperpingu/bitboards.git"}
eframe = { version = "0.34", features=["persistence"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[lints]
workspace = true


[lib]
name="hex_game"